"use client";
import { useEffect, useMemo, useState } from "react";
import { useParams } from "next/navigation";
import { Card } from "@/components/ui";
import { getSupabaseClient } from "@/lib/supabase";

type Member={id:string; player_profile_id:string; display_name:string; linked_auth_user_id:string|null; is_active:boolean};
export default function GroupDetailPage(){ const {id}=useParams<{id:string}>(); const [tab,setTab]=useState("メンバー管理"); const [members,setMembers]=useState<Member[]>([]); const [name,setName]=useState(""); const [linkId,setLinkId]=useState(""); const [error,setError]=useState("");
const load=async()=>{const s=getSupabaseClient(); if(!s||!id) return; const {data}=await s.from("club_members").select("id,player_profile_id,is_active,player_profiles(display_name,linked_auth_user_id)").eq("club_id",id).order("created_at",{ascending:true}); setMembers((data??[]).map((r:any)=>({id:r.id,player_profile_id:r.player_profile_id,display_name:r.player_profiles?.display_name??"名称未設定",linked_auth_user_id:r.player_profiles?.linked_auth_user_id??null,is_active:r.is_active!==false})));};
useEffect(()=>{void load();},[id]);
const activeMembers=useMemo(()=>members.filter((m)=>m.is_active),[members]);
const addMember=async()=>{const s=getSupabaseClient(); if(!s||!id||!name.trim()) return; const {data:pp,error:pe}=await s.from("player_profiles").insert({display_name:name.trim(),linked_auth_user_id:linkId.trim()||null,is_active:true}).select("id").single(); if(pe||!pp?.id){setError("メンバー追加に失敗しました"); return;} await s.from("club_members").insert({club_id:id,player_profile_id:pp.id,is_active:true}); setName(""); setLinkId(""); setError(""); await load();};
const updateMember=async(m:Member,newName:string,newLink:string)=>{const s=getSupabaseClient(); if(!s||!newName.trim()) return; await s.from("player_profiles").update({display_name:newName.trim(),linked_auth_user_id:newLink.trim()||null}).eq("id",m.player_profile_id); await load();};
const deactivate=async(m:Member)=>{const s=getSupabaseClient(); if(!s) return; await s.from("club_members").update({is_active:false}).eq("id",m.id); await load();};
return <main className="mx-auto flex min-h-screen w-full max-w-md flex-col gap-4 p-4"><h1 className="text-xl font-bold">グループ詳細</h1><div className="grid grid-cols-3 gap-2 text-xs">{["メンバー管理","グループ戦績","個人ランキング","ペアランキング","イベント履歴"].map((t)=><button key={t} className={`rounded-lg px-2 py-2 ${tab===t?"bg-accent text-black":"bg-zinc-800 text-zinc-200"}`} onClick={()=>setTab(t)}>{t}</button>)}</div>{tab==="メンバー管理"?<Card title="メンバー管理"><div className="space-y-2"><p className="text-xs text-zinc-300">在籍メンバー: {activeMembers.length}人</p><input className="w-full rounded-xl bg-zinc-800 p-3" placeholder="メンバー名" value={name} onChange={(e)=>setName(e.target.value)} /><input className="w-full rounded-xl bg-zinc-800 p-3" placeholder="auth user id（任意）" value={linkId} onChange={(e)=>setLinkId(e.target.value)} />{error&&<p className="text-sm text-red-400">{error}</p>}<button className="w-full rounded-xl bg-accent py-3 font-semibold text-black" onClick={addMember}>定常メンバー追加</button><div className="space-y-2">{members.map((m)=><MemberRow key={m.id} member={m} onSave={updateMember} onDeactivate={deactivate} />)}</div></div></Card>:<Card title={tab}><p className="text-sm text-zinc-300">この機能は次タスクで実装予定です。</p></Card>}</main>; }

function MemberRow({member,onSave,onDeactivate}:{member:Member;onSave:(m:Member,n:string,l:string)=>Promise<void>;onDeactivate:(m:Member)=>Promise<void>;}){ const [editing,setEditing]=useState(false); const [n,setN]=useState(member.display_name); const [l,setL]=useState(member.linked_auth_user_id??""); return <div className="rounded-xl bg-zinc-800 p-3"><p className="text-xs text-zinc-400">{member.is_active?"在籍":"非表示/退会"}</p>{editing?<div className="space-y-2"><input className="w-full rounded-lg bg-zinc-700 p-2" value={n} onChange={(e)=>setN(e.target.value)} /><input className="w-full rounded-lg bg-zinc-700 p-2" value={l} onChange={(e)=>setL(e.target.value)} placeholder="auth user id（任意）" /><div className="flex gap-2"><button className="w-1/2 rounded-lg bg-accent py-2 text-black" onClick={async()=>{await onSave(member,n,l); setEditing(false);}}>保存</button><button className="w-1/2 rounded-lg border border-zinc-500 py-2" onClick={()=>setEditing(false)}>キャンセル</button></div></div>:<div className="space-y-1"><p className="font-semibold">{member.display_name}</p><p className="text-xs text-zinc-300">連携: {member.linked_auth_user_id??"未設定"}</p>{member.is_active&&<div className="flex gap-2"><button className="rounded border border-zinc-500 px-3 py-1 text-sm" onClick={()=>setEditing(true)}>編集</button><button className="rounded border border-red-500 px-3 py-1 text-sm text-red-300" onClick={()=>void onDeactivate(member)}>非表示/退会</button></div>}</div>}</div>; }
